---
title: "Estimating CWM"
author: "Annegreet Veeken"

output: html_document
---

```{r load packages}
library(tidyverse)
library(rjags)
library(runjags)
library(mcmc)
library(coda)
library(xlsx)
```

```{r load gapfilled data, echo=FALSE}
# 
memory.limit(size = 9999999)
## Species per pollen type list
spec <- readRDS("RDS_files/01_PollenType_species.rds") %>% as_tibble()

# filter out aquatic species
spec <- spec %>% 
  filter(StdValue < 10 | is.na(StdValue)) 
spec$pollentaxon[spec$pollentaxon == "Sambucus nigra"] <- "Sambucus.nigra"
spec <- spec %>% 
  dplyr::select(stand.spec, pollentaxon) %>% 
  filter(!pollentaxon == "NA" & !is.na(stand.spec)) %>% 
  distinct()

# check for duplicate values (species assigned to two or more pollen type) 
duplicats <- table(spec$stand.spec) %>% 
  data.frame() %>% filter(Freq > 1) 

## Gap-filled trait data
gapdata <- readRDS("RDS_files/Gap_filled_traits_2020.rds") 
gapdata <- gapdata %>% filter(Species %in% spec$stand.spec) # only the relevant species

# merge trait data with spec/pol list
trait <- gapdata %>% 
  inner_join(spec, by = c("Species" = "stand.spec")) %>% 
  arrange(pollentaxon) # sort alphabetically

# Pollen data
lPOL <- readRDS("RDS_files/04_PollenWEU-PPEcorrected-unbinned.rds")
```

# All taxa
```{r cmw model log, eval=FALSE}
# convert pollen data to data frame
sitenames <- names(lPOL)
pol <-
  purrr::map2(lPOL, sitenames, ~.x %>% 
                ungroup() %>% as.data.frame() %>%
                rename(taxa = ppe.taxon) %>% 
  dplyr::select(age, taxa, adjustedpercent) %>%
  # covert to wide format
  spread(., key = taxa, value = adjustedpercent) %>%
  mutate(age = as.numeric(age),
         site.name = .y)) %>% # add site.name  
  # bind all data frames in list
  bind_rows() %>%
  # set all pollen not present at a site to zero
  replace(is.na(.), 0) %>% 
  # order columns alphabetically
  dplyr::select(site.name, age, order(colnames(.))) %>% 
  # order rows
  arrange(site.name, age) 

pollentaxa <- pol %>%
  dplyr::select(-site.name, -age) %>%
  colnames(.)


cwmlogfunc <- function(x){
Trait <- trait %>%
  filter(pollentaxon %in% pollentaxa) %>%
  pull(x)

Tax <- trait %>%
  filter(pollentaxon %in% pollentaxa) %>%
  pull(pollentaxon) %>% 
  as.factor()

N <- length(Trait)

Ab <- pol %>%
  dplyr::select(-site.name, -age) %>%
  as.matrix()
Ntax <- ncol(Ab)
Nyr <- nrow(Ab) 

# for setting priors taxon level
Mean <- mean(Trait)
SD <- sd(Trait)

cat("model {
for (i in 1:Nyr){
cwm[i] ~ dnorm(mean.tax[r[i]], tau.tax[r[i]])
r[i] ~ dcat(Ab[i, 1:Ntax])
}

for (i in 1:N) {
      Trait[i] ~ dlnorm(mean.tax[Tax[i]], tau.tax[Tax[i]])
}

for (l in 1:Ntax){
# vague priors taxon level
    mean.tax[l] ~ dnorm(0, 10^-4)
    tau.tax[l] ~ dgamma(0.001, 0.001)
    sd.tax[l] <- sqrt(1/tau.tax[l])
}

#data# N, Nyr, Trait, Tax, Ntax, Ab
#monitor# cwm
#inits# mean.tax, tau.tax
}", file = "CWMmodel_mix.txt")

# initial values
mean.tax <- list(chain1 = rep(min(Trait),Ntax), chain2 = rep(max(Trait),Ntax))
tau.tax <- list(chain1 = rep(1/(SD*0.1)^2,Ntax), chain2 = rep(1/(SD*10)^2, Ntax))

results <- run.jags("CWMmodel_mix.txt", n.chains = 2, sample = 5000)

# saveRDS(results, paste("RDS_files/Posterior_CWM_unbinned/05_Stats_CWM_estimates_", x,".rds", sep = ""))
# plot a couple parameter to check convergence
params <- c("cwm[1]", "cwm[1000]", "cwm[3000]","cwm[5000]","cwm[7000]")

plot(results, vars = params, file = 
       paste("Convergence_diag_unbinned_", x, ".pdf", sep = ""))

res <- as.matrix(summary(results))

saveRDS(res, paste("RDS_files/05_CWM_estimates_unbinned_", x,".rds", sep =""))
}

normaltraits <- c("SLA","LA","LeafC","LeafP","LeafN","Seed.lenght","Seed.count","Seed.mass")
purrr::map(normaltraits, ~cwmlogfunc(.))
```

```{r ldmc all taxa}
sitenames <- names(lPOL)
pol <-
  purrr::map2(lPOL, sitenames, ~.x %>% 
                ungroup() %>% as.data.frame() %>%
                rename(taxa = ppe.taxon) %>% 
  dplyr::select(age, taxa, adjustedpercent) %>%
  # covert to wide format
  spread(., key = taxa, value = adjustedpercent) %>%
  mutate(age = as.numeric(age),
         site.name = .y)) %>% # add site.name  
  # bind all data frames in list
  bind_rows() %>%
  # set all pollen not present at a site to zero
  replace(is.na(.), 0) %>% 
  # order columns alphabetically
  dplyr::select(site.name, age, order(colnames(.))) %>% 
  # order rows
  arrange(site.name, age)
 
pollentaxa <- pol %>%
  dplyr::select(-site.name, -age) %>%
  colnames(.)

Trait <- trait %>%
  filter(pollentaxon %in% pollentaxa) %>%
  pull(LDMC)

Tax <- trait %>%
  filter(pollentaxon %in% pollentaxa) %>%
  pull(pollentaxon) %>% 
  as.factor()

N <- length(Trait)

Ab <- pol %>%
  dplyr::select(-site.name, -age) %>%
  as.matrix()
Ntax <- ncol(Ab)
Nyr <- nrow(Ab) 

# for setting priors taxon level
Mean <- mean(Trait)
SD <- sd(Trait) 

cat("model {
for (i in 1:Nyr){
cwm[i] ~ dbeta(alpha.tax[r[i]], beta.tax[r[i]])
r[i] ~ dcat(Ab[i, 1:Ntax])
}

for (i in 1:N) {
      Trait[i] ~ dbeta(alpha.tax[Tax[i]], beta.tax[Tax[i]])
}
for (l in 1:Ntax){
# vague priors taxon level
    alpha.tax[l] <- mean.tax[l] * sd.tax[l] 
    beta.tax[l] <- (1 - mean.tax[l]) * sd.tax[l]
    mean.tax[l] ~ dnorm(0, 10^-4) 
    sd.tax[l]  ~ dgamma(0.001,0.001)
}

#data# N, Nyr, Trait, Tax, Ntax, Ab
#monitor# cwm
#inits# mean.tax, sd.tax
}", file = "CWMmodel_beta_mix.txt")

# initial values
mean.tax <- list(chain1 = rep(min(Trait),Ntax), chain2 = rep(max(Trait),Ntax))
sd.tax <- list(chain1 = rep(1/(SD*0.1)^2,Ntax), chain2 = rep(1/(SD*10)^2, Ntax))

results <- run.jags("CWMmodel_beta_mix.txt", n.chains = 2)

# saveRDS(results, "RDS_files/posterior_CWM_unbinned/05_Stats_CWM_estimates_LDMC.rds")
# plot a couple parameter to check convergence
params <- c("cwm[1]", "cwm[1000]", "cwm[3000]","cwm[5000]","cwm[7000]")

plot(results, vars = params, file = "Convergence_diag_unbinned_LDMC.pdf")

res <- as.matrix(summary(results))

saveRDS(res, "RDS_files/05_CWM_estimates_unbinned_LDMC.rds")
```

```{r plant height all taxa}
# Plant height (not in gapfilled data)
TRYdata <- read.csv("Data/24082020TRY_long_cleaned.csv")
TRYdata <- TRYdata %>% filter(AccSpeciesName %in% spec$stand.spec)

TRYdata <- TRYdata %>%
  # convert cm to m
  mutate(StdValue.m = ifelse(UnitName == "cm", StdValue/100, StdValue)) %>% 
  filter(CleanTraitName == "plant_height_generative") %>% 
  # join with pollen list
  left_join(spec, by = c("AccSpeciesName" = "stand.spec"))

Trait <- TRYdata %>%
  filter(pollentaxon %in% pollentaxa) %>%
  pull(StdValue.m)

Tax <- TRYdata %>%
  filter(pollentaxon %in% pollentaxa) %>%
  filter(CleanTraitName == "plant_height_generative") %>%
  pull(pollentaxon) %>% 
  as.factor()

N <- length(Trait)

Ab <- pol %>%
  dplyr::select(-site.name,-age) %>%
  as.matrix()
Ntax <- ncol(Ab)
Nyr <- nrow(Ab) 

# for setting priors taxon level
Mean <- mean(Trait)
SD <- sd(Trait)

# initial values
mean.tax <- list(chain1 = rep(min(Trait),Ntax), chain2 = rep(max(Trait),Ntax))
tau.tax <- list(chain1 = rep(1/(SD*0.1)^2,Ntax), chain2 = rep(1/(SD*10)^2, Ntax))

results <- run.jags("CWMmodel_mix.txt", n.chains = 2)

# saveRDS(results, "RDS_files/posterior_CWM_unbinned/05_Stats_CWM_estimates_PlantHeight.rds")
# plot a couple parameter to check convergence
# plot a couple parameter to check convergence
params <- c("cwm[1]", "cwm[1000]", "cwm[3000]","cwm[5000]","cwm[7000]")

plot(results, vars = params, file = 
       "Convergence_diag_unbinned_PlantHeight.pdf")

res <- as.matrix(summary(results))

saveRDS(res, "RDS_files/05_CWM_estimates_unbinned_PlantHeight.rds")
```

```{r compile estimates}
# all taxa
files <- 
  list.files("RDS_files//") %>% 
  str_subset(pattern = "05_CWM_estimates_")
files <- files[!str_detect(files, pattern = "Stats")]
files <- files[!str_detect(files, pattern = "herbs")]
files <- files[!str_detect(files, pattern = "trees")]


traitname <- files %>% 
  str_remove(., "05_CWM_estimates_unbinned_") %>% 
  str_remove(., ".rds")
sitelabels <- pol %>% 
  dplyr::select(site.name, age)

folderpath.fun <- function(x)
{paste("RDS_files/", x, sep = "/")}

dfCWM <- files %>% 
  folderpath.fun(.) %>% 
  purrr::map2(traitname, ~readRDS(.) %>% 
               as.data.frame() %>% 
               rownames_to_column("parameter") %>% 
               filter(., str_detect(parameter, "cwm\\[")) %>% 
               dplyr::select(Mean, SD) %>%  
               mutate(trait = .y) %>% 
               bind_cols(sitelabels,.)) %>% 
  bind_rows()

saveRDS(dfCWM,"RDS_files/05_Posterior_alltraits_unbinned.rds")
```
