---
title: "PCA"
output: html_notebook
---

```{r}
library(tidyverse)
library(ggplot2)
library(ggfortify)
library(ggmap)
```

```{r prepare data}
dfCWM <- readRDS("RDS_files/05_Posterior_alltraits_unbinned.rds")
dfAGRI <- readRDS("RDS_files/Archaeological_indicators.rds") %>% 
   filter(age <= 10000) %>% 
  select(site.name, age, PresenceAgri) %>% 
  distinct()

dfCWM <- dfCWM %>% 
  left_join(., dfAGRI, by = c("site.name", "age")) %>%
  dplyr::select(site.name, age, trait, Mean, SD, PresenceAgri)

# re-order levels
dfCWM$PresenceAgri <- factor(dfCWM$PresenceAgri, levels = c("Before agriculture", 
                                                          "After agriculture"))

traitlab <-  c("SLA" = "Specific leaf area", "PH" ="Plant height","LDMC" = "Leaf dry matter content",
               "LA" = "Leaf area", "LeafC" = "Leaf carbon", "LeafN" =  "Leaf nitrogen", 
               "LeafP" =  "Leaf phosphorus", "Seed.count" = "Seed count", "Seed.lenght" = "Seed length",
               "Seed.mass" = "Seed mass")
```

```{r}
dfPCA <- dfCWM %>% 
  dplyr::select(-SD) %>% 
  spread(trait, Mean)
pca <- dfPCA %>% 
  dplyr::select(-site.name, -age, -PresenceAgri) %>% 
  prcomp(., scale. = TRUE)

pca_sum <- summary(pca)

pca_points <- 
  #  convert the pca results to a tibble
  as_tibble(pca$x) %>% 
  bind_cols(dfCWM[dfCWM$trait == "LA", c("site.name","age", "PresenceAgri")])

pca_hull <- 
  pca_points %>% 
  group_by(PresenceAgri) %>% 
  slice(chull(PC1, PC2))

pca_load <- 
  as_tibble(pca$rotation, rownames = 'variable') %>% 
  mutate(variable = dplyr::recode(variable,
                                  "SLA" = "Specific leaf area", 
                                  "PlantHeight" ="Plant height",
                                  "LDMC" = "Leaf dry matter content",
                                  "LA" = "Leaf area", 
                                  "LeafC" = "Leaf carbon", 
                                  "LeafN" =  "Leaf nitrogen",  
                                  "LeafP" =  "Leaf phosphorus", 
                                  "Seed.count" = "Seed count", 
                                  "Seed.lenght" = "Seed length",
                                  "Seed.mass" = "Seed mass"))

l <- ggplot(pca_points, aes(x = PC1, y = PC2)) +
  geom_point(aes(colour = PresenceAgri)) +
  geom_polygon(data = pca_hull, aes(fill = PresenceAgri, colour = PresenceAgri),
               alpha = 0.1,
               show.legend = FALSE) +
  geom_segment(data = pca_load, 
               aes(x = 0, y = 0, 
                   xend = PC1*9,
                   yend = PC2*9),
               arrow = arrow(length = unit(1/2, 'picas'))) +
  annotate('text', x = c(3.9,-5,-4.1, 4.85,5,
                         -3.45,-3.07,-2.97,-1.94,5.1), 
           y = c(-2.62,-1,1.49,-0.53,0.42,
                 -1.47,4.47,-5.3,-6.07,-1.2),
           label = pca_load$variable,
           size = 4) +
  scale_x_continuous(name = paste0("PC1 (", round(100 * pca_sum$importance[2,"PC1"],2), "%)")) +
  scale_y_continuous(name = paste0("PC2 (", round(100 * pca_sum$importance[2,"PC2"],2), "%)")) +
  theme_bw() +
  theme(legend.position = "bottom",
        text = element_text(size = 12),
        legend.text = element_text(size = 12),
        plot.margin=grid::unit(c(1,1,1,1), "cm")) +
  scale_color_manual(values = c("#999999","#E69F00"), 
                     aesthetics = c("colour", "fill"),
                     name = "") 
l

ggsave("Figures/Fig3-PCA.pdf", l, dpi = 600, width = 174, 
       height = 174, units = "mm")

pca_hull <- 
  pca_points %>% 
  group_by(PresenceAgri) %>% 
  slice(chull(PC2, PC3))
lab_pos <- tibble(labels = pca_load$variable, 
                  x = c(-2.6,-1.2, 1.5,-0.5,1.3,-1.5,4,-5.2, -6.07, -1.2), 
                  y = c(3.7,2.9,4.5,3.4,2.8,5.5,2.6,-1.1,-0.6,2))

g <- ggplot(pca_points, aes(x = PC2, y = PC3)) +
  geom_point(aes(colour = PresenceAgri)) +
  geom_polygon(data = pca_hull, aes(fill = PresenceAgri, colour = PresenceAgri),
               alpha = 0.1,
               show.legend = FALSE) +
  geom_segment(data = pca_load, 
               aes(x = 0, y = 0, 
                   xend = PC2*9,
                   yend = PC3*9),
               arrow = arrow(length = unit(1/2, 'picas'))) +
  annotate('text', x = lab_pos$x, y = lab_pos$y,
           label = pca_load$variable,
           size = 3.5) +
  scale_x_continuous(name = paste0("PC2 (", round(100 * pca_sum$importance[2,"PC2"],2), "%)")) +
  scale_y_continuous(name = paste0("PC3 (", round(100 * pca_sum$importance[2,"PC3"],2), "%)")) +
  theme_bw() +
  theme(legend.position = "bottom",
        text = element_text(size = 12)) +
  scale_color_manual(values = c("#999999","#E69F00"), 
                     aesthetics = c("colour", "fill"),
                     name = "") 
g
# ggsave("Figures/SI3-PCA23_agri.png", g, dpi = 600, width = 170, height = 170, units = "mm")


pca_hull <- 
  pca_points %>% 
  group_by(PresenceAgri) %>% 
  slice(chull(PC1, PC3))
lab_pos <- tibble(labels = pca_load$variable, 
                  x = c(4.2,-5,-4.3,5,5,-3.1, -3.4,-3.3,-1,5.5), 
                  y = c(4.6,3.5,5.3,4,3.3,7,2.8,-0.7,-0.7,1.9))

p <- ggplot(pca_points, aes(x = PC1, y = PC3)) +
  geom_point(aes(colour = PresenceAgri)) +
  geom_polygon(data = pca_hull, aes(fill = PresenceAgri, colour = PresenceAgri),
               alpha = 0.1,
               show.legend = FALSE) +
  geom_segment(data = pca_load, 
               aes(x = 0, y = 0, 
                   xend = PC1*10,
                   yend = PC3*10),
               arrow = arrow(length = unit(1/2, 'picas'))) +
  annotate('text', x =lab_pos$x, y = (pca_load$PC3*10),
           label = pca_load$variable,
           size = 3.5) +
  scale_x_continuous(name = paste0("PC1 (", round(100 * pca_sum$importance[2,"PC1"],2), "%)")) +
  scale_y_continuous(name = paste0("PC3 (", round(100 * pca_sum$importance[2,"PC3"],2), "%)")) +
  theme_bw() +
  theme(legend.position = "bottom",
        text = element_text(size = 12)) +
  scale_color_manual(values = c("#999999","#E69F00"), 
                     aesthetics = c("colour", "fill"),
                     name = "") 
p
# ggsave("Figures/SI3-PCA13_agri.png", p, dpi = 600, width = 170, height = 170, units = "mm")


```

```{r PCA maps}
sites <- readRDS("RDS_files/03_PollenWEU-Harmonised.rds") %>% 
  purrr::map(., ~dplyr::select(., site.name, lat, long) %>% 
              unique) %>% 
  bind_rows()

timecat <- c(-200, seq(from = 1000, to = 8000, by = 1000),10000, Inf)
timecat.lab <- c("0-1000 BP", "1000-2000 BP", "2000-3000 BP", "3000-4000 BP", "4000-5000 BP",
             "5000-6000 BP", "6000-7000 BP", "7000-8000 BP", "8000-10000 BP")


df <- left_join(pca_points, sites, by = c("site.name" = "site.name")) %>% 
  mutate(., time.bin = cut(as.numeric(age), breaks = timecat,right = TRUE,
                           labels = c(timecat.lab,NA))) %>% 
  select(PC1, site.name:time.bin)

eu <- ggplot2::map_data("world", 
                        region = c("UK", "Ireland","Netherlands",
                                   "Germany", "France", "Denmark",
                                   "Sweden", "Switzerland",
                                   "Belgium", "Czech Republic",
                                   "Austria", "Luxembourg"))
eumap <- ggplot() + 
  geom_polygon(data = eu, aes(x = long, y = lat, group = group),
                              colour = "#999999", fill = "#999999", 
               show.legend = FALSE) +
  coord_map("sinusoidal")

(pcamap <- eumap + 
  geom_point(data = df[df$PresenceAgri == "After agriculture",],
             aes(x = long, y = lat), pch = 21, fill = NA, colour = "black", size = 2) +
  geom_point(data = df, aes(x = long, y = lat, color = PC1), size = 1.5) +
  scale_x_continuous("") +
  scale_y_continuous("") +
  ggtitle("") +
  scale_color_viridis_c() +
  theme_bw() +
  theme(text = element_text(size = 12),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom") +
  facet_wrap(~time.bin, ncol = 3))
ggsave("Figures/Fig4-PCA-map.pdf", pcamap,  
       width = 174, 
       height = 174, units = "mm", dpi = 600)

``` 

```{r}
compscores <- pca_load <- 
  as_tibble(pca$rotation, rownames = 'variable') %>% 
  mutate(variable = dplyr::recode(variable,
                                  "SLA" = "Specific leaf area", 
                                  "PlantHeight" ="Plant height",
                                  "LDMC" = "Leaf dry matter content",
                                  "LA" = "Leaf area", 
                                  "LeafC" = "Leaf carbon", 
                                  "LeafN" =  "Leaf nitrogen",  
                                  "LeafP" =  "Leaf phosphorus", 
                                  "Seed.count" = "Seed count", 
                                  "Seed.lenght" = "Seed length",
                                  "Seed.mass" = "Seed mass")) %>% 
  select(variable, PC1,PC2,PC3) %>% 
  arrange(PC1,PC2,PC3) %>% 
  mutate(PC1 = round(PC1, digits = 3),
    PC2 = round(PC2, digits = 3),
    PC3 = round(PC3, digits = 3)) 
compscores  
  
  
write.csv(compscores, "Output/Sample_scores_CWM_PCA.csv", row.names = FALSE)

```

